### ISSUE TITLE
499 Client Error: status code 499 for url on Joplin_testbed.ipynb

### ISSUE THREAD

**Issue by rkn2** [IN-CORE/pyincore#540] opened 2024-04-11 13:46 UTC
Hi I was running this notebook fine yesterday and the day before
https://incore.ncsa.illinois.edu/doc/incore/notebooks/Joplin_testbed/Joplin_testbed.html

But today I keep getting this error: HTTPError: 499 Client Error: status code 499 for url: https://incore.ncsa.illinois.edu/hazard/api/tornadoes/5d07cbeab9219c065b080930/values  

Prior to this error I had gotten: 
ERROR 1: PROJ: proj_create_from_database: Open of /opt/conda/share/proj failed
Connection successful to IN-CORE services. pyIncore version detected: 1.17.0 
right after I had done the client = InCoreClient() part. 

However the sections after that for doing the visualization of buildings by archetype and tornado path worked as well as calculating the fragility curves. 

The code block that I got the error on was this: 
```
bldg_dmg.run_analysis()  # Run the building damage module to get building damage results for Joplin in a .csv file format. 
                         # The building damage results herein are referred to fragilities at three damage states (moderate, 
                         # heavy, complete) for 28152 buildings located in Joplin that fall within the tornado path or not.
building_dmg_result = bldg_dmg.get_output_dataset('ds_result')
# Convert dataset to Pandas DataFrame
df_bldg_dmg = building_dmg_result.get_dataframe_from_csv()
# Display top 5 rows of output data
df_bldg_dmg.head()

```

I tried shutting down Jupyter and killing the kernel as well as redownloading the .ipynb but the error persisted. Additionally I tried checking the version of pyproject
```
import pyproj
print(pyproj.__version__)` and setting the environment `import os
os.environ['PROJ_LIB'] = '/opt/conda/share/proj'
print('done')
```
 which got rid of the ERROR 1 but as I continued on with the code it still broke at hte point mentioned above.  Attached is the full error in case that is helpful:
![image](https://github.com/IN-CORE/pyincore/assets/22533171/067dd955-53ca-4cbd-888b-1f541d2de36f)
![image](https://github.com/IN-CORE/pyincore/assets/22533171/5c8b1672-dd9f-47fa-aacb-47be94913775)
Thank you very much for your time and help!

**Comment by navarroc** [comment] 2024-04-11 19:50
Thanks for reporting this. I'm going to close this issue since it's a networking issue that is being investigated. If you are on the IN-CORE mailing list you should get a notification when the issue is resolved.

**Closed by navarroc** 2024-04-11 19:50 UTC
